on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Set up variables
      - name: Set Docker tags
        id: docker_tags
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "TAGS=latest" >> $GITHUB_ENV
          else
            echo "TAGS=${{ github.sha }}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rdoy-lab/backstage-app:${{ env.TAGS }}, rdoy-lab/backstage-app:${{ github.sha }}
